services:
  app:
    build: . 
    ports:
      - "${PORT}:5000"
    env_file:
      - ./.env
    depends_on:
      - mongo

  #  MongoDB
  mongo:
    image: mongo:latest # image resmi MongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: