GET http://localhost:5000/?name=dgsdgfa


###
GET http://localhost:5000/api/progress

### create activity log
POST http://localhost:5000/api/progress/activityLog
Content-Type: application/json

{
  "userId": "123",
  "activityName": "bermain tic tac toe",
  "activityDuration": 60,
  "score": 90,
  "comment": "apa lah ini cik"
}

### get activity log by user
GET http://localhost:5000/api/progress/activityLog/123



### get activity recommendation by users
GET http://localhost:5000/api/progress/recommendation/123